# Banco de dados PostgreSQL
spring:
  profiles:
    active: dev
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/postgres?currentSchema=bytekids
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: MeuHikariPool
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

---
# Banco de dados em memória para testes
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect